In [23]:
import numpy as np

array=np.arange(1,101)
array=array.reshape((10,10))
print(array)

print("SECOND ROW= ",array[2])
print("LAST COLUMN =",array[:,-1])
print("ELEMENT AT (5,7)=",array[5,7])
even=np.where(array%2==0,-1,array)
print("NEW ARRAY WITH EVEN AS -1\n",even)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
SECOND ROW=  [21 22 23 24 25 26 27 28 29 30]
LAST COLUMN = [ 10  20  30  40  50  60  70  80  90 100]
ELEMENT AT (5,7)= 58
NEW ARRAY WITH EVEN AS -1
 [[ 1 -1  3 -1  5 -1  7 -1  9 -1]
 [11 -1 13 -1 15 -1 17 -1 19 -1]
 [21 -1 23 -1 25 -1 27 -1 29 -1]
 [31 -1 33 -1 35 -1 37 -1 39 -1]
 [41 -1 43 -1 45 -1 47 -1 49 -1]
 [51 -1 53 -1 55 -1 57 -1 59 -1]
 [61 -1 63 -1 65 -1 67 -1 69 -1]
 [71 -1 73 -1 75 -1 77 -1 79 -1]
 [81 -1 83 -1 85 -1 87 -1 89 -1]
 [91 -1 93 -1 95 -1 97 -1 99 -1]]


In [30]:
A=np.arange(1,26)
A=A.reshape((5,5))
B=np.arange(1,6)
C=A+B
print("ADDING B TO EACH ROW OF A\n",C)

print("MULTIPLY EACH ROW BY B\n",A*B)

ADDING B TO EACH ROW OF A
 [[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]
MULTIPLY EACH ROW BY B
 [[  1   4   9  16  25]
 [  6  14  24  36  50]
 [ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]]
